### PR TITLE
Modified to work with OpenCV 4.0-Alpha

### PR DESCRIPTION
**Pull request by TechnikEmpire**
Switched to OpenCV 4.0 and then made all necessary fixes for compilation and tests to succeed.

### CODE REVIEW

**Comment by TechnikEmpire** [comment]
If you can review, the I might not have changed the `MOUSE*` events to the correct ones. Pretty sure I did, but their new enum system is a little, well, new and confusing as there is overlap in naming.

**Comment by ereator** [comment]
Thank you for your contribution and details towards the performance. Currently we do not use DNNs but plan to start using them in the very next version.
In order to build the project under Windows I had also perform some additional changes:
- CvScalat -> cv::Scalar
- CvRect -> cv::Rect
- remove CV_USRTYPE1

**Comment by TechnikEmpire** [comment]
You guys seem like you're much more skilled in this area than I. If you guys are able to rewrite the convolution layer in OpenCV dnn to use AMP, you would get amazing performance. Their convolution layer is the bottleneck. I tried but failed. That would be super awesome.

**Comment by ereator** [comment]
That may take us another half year :-) But yes, parallelizing the convolutional layer of OpenCV DNNs module would be extremely interesting!

**Comment by TechnikEmpire** [comment]
Yeah that code is just brutal. Uses a class that splits the work across functors across threads across stripes, not a single comment (except a useless comment about zeroing memory over a memset call) and variable names are about as specific as "var". Anyway, thanks for your replies.

**Pull request merged**
